Backthen there was a library named matlab which has mathematical funcs. So, the researcher thought of making/creating library in python, It is numpy

Numpy - Numerical Python

In [41]:
import numpy as np

In [42]:
l=[1,2,3,4,5]

Creating array : 2 types np.array and np.asarray and np.asanyarray

In [43]:
arr = np.array(l)

In [44]:
arr

array([1, 2, 3, 4, 5])

In [45]:
arr2 = np.asarray((1,2,3,4,5))

In [46]:
arr2

array([1, 2, 3, 4, 5])

In [47]:
arr3 = np.asarray((12,22,33,4,75))

In [48]:
arr3

array([12, 22, 33,  4, 75])

Dimension

In [49]:
arr.ndim

1

In [50]:
arr2.ndim

1

In [51]:
arr3.ndim

1

In [52]:
arr4 = np.array([[1,2,3],[4,5,6]])

In [53]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr4.ndim

2

Matrix - also a type of array
* Matrix is always of 2 dimensions no  matter what but array can be any dimension
* It's already a array so when we try to use np.array it doesn't do anything

In [55]:
mat = np.matrix(l)

In [56]:
mat

matrix([[1, 2, 3, 4, 5]])

In [57]:
np.asarray(mat)

array([[1, 2, 3, 4, 5]])

In [58]:
arr

array([1, 2, 3, 4, 5])

In [59]:
arr3

array([12, 22, 33,  4, 75])

Arrays do shallow copy

In [60]:
arr = arr3

In [61]:
arr

array([12, 22, 33,  4, 75])

In [62]:
arr3

array([12, 22, 33,  4, 75])

In [63]:
arr[0]=595

In [64]:
arr

array([595,  22,  33,   4,  75])

In [65]:
arr3

array([595,  22,  33,   4,  75])

To do deep copy

In [66]:
arr5 = np.copy(arr)

In [67]:
arr5

array([595,  22,  33,   4,  75])

In [68]:
arr

array([595,  22,  33,   4,  75])

In [69]:
arr[0] = 485

In [70]:
arr

array([485,  22,  33,   4,  75])

In [71]:
arr5

array([595,  22,  33,   4,  75])

Functions in array

Shape

In [73]:
arr5.shape

(5,)

In [77]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr4.shape

(2, 3)

Size

In [80]:
arr4.size

6

In [82]:
arr.size

5

Data Type

In [83]:
arr.dtype

dtype('int32')

In [84]:
arr4.dtype

dtype('int32')

In [85]:
arr6 = np.array(['shiv','sush','heer','sahithi','thiru'])

In [86]:
arr6

array(['shiv', 'sush', 'heer', 'sahithi', 'thiru'], dtype='<U7')

In [87]:
arr6.dtype

dtype('<U7')

From Function : here 2,3 is dimension
* 0==0, 0==1,0==2
* 1==0,1==1,1==2

In [89]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [93]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [91]:
(i*i for i in range(5))

<generator object <genexpr> at 0x000002A23E560580>

In [92]:
iteration = (i*i for i in range(5))

From Iter

In [97]:
np.fromiter(iteration,float)

array([ 0.,  1.,  4.,  9., 16.])

From String

In [105]:
np.fromstring('Dont sit',sep=' ')

C:\Users\SHIVANI\AppData\Local\Temp\ipykernel_38264\4154011216.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Dont sit',sep=' ')


array([], dtype=float64)

In [106]:
np.fromstring('25 30 40',sep=' ')

array([25., 30., 40.])

In [113]:
np.fromstring('25 30 40',sep=' ').dtype

dtype('float64')

In [108]:
arr7=  np.fromstring('2,3,40,89',sep=',')

In [109]:
arr7

array([ 2.,  3., 40., 89.])

In [110]:
arr7.ndim

1

In [111]:
arr7.shape

(4,)

In [112]:
arr7.dtype

dtype('float64')