Sort,search and counting funcs

In [113]:
import numpy as np

In [114]:
arr  = np.random.randint(1,10,(1,7))

In [115]:
arr

array([[4, 1, 6, 7, 7, 4, 4]])

By default Ascending order

In [116]:
arr

array([[4, 1, 6, 7, 7, 4, 4]])

In [117]:
arr.sort()

In [118]:
arr

array([[1, 4, 4, 4, 6, 7, 7]])

In [119]:
np.sort(arr)

array([[1, 4, 4, 4, 6, 7, 7]])

In [120]:
arr

array([[1, 4, 4, 4, 6, 7, 7]])

In [121]:
np.sort(arr)

array([[1, 4, 4, 4, 6, 7, 7]])

searchsorted - gives the index where the element has to  be inserted in the given sorted array

In [122]:
np.searchsorted(arr,46)

ValueError: object too deep for desired array

In [ ]:
np.searchsorted(arr,3)

0

In [ ]:
arr1=np.array([1,0,2,3,4,99,5,80])

In [ ]:
arr1

array([ 1,  0,  2,  3,  4, 99,  5, 80])

Counting Functions

In [ ]:
np.count_nonzero(arr1)

7

where : Returns indexes where condition satisfies

In [ ]:
np.where(arr1>10)

(array([5, 7], dtype=int64),)

Gives values directly instead of indexes

In [ ]:
np.extract(arr1>2,arr1)

array([ 3,  4, 99,  5, 80])

Byte Swapping - represents the data in internal bytes order

In [ ]:
arr1

array([ 1,  0,  2,  3,  4, 99,  5, 80])

ByteSwap - gives the byte representation, internally in bytes how it is stored

In [ ]:
arr.byteswap()

array([ 167772160,  335544320,  503316480,  671088640,  838860800,
       1006632960])

In [ ]:
arr

array([10, 20, 30, 40, 50, 60])

For inplace byteswap

In [ ]:
arr.byteswap(True)

array([ 167772160,  335544320,  503316480,  671088640,  838860800,
       1006632960])

In [ ]:
arr

array([ 167772160,  335544320,  503316480,  671088640,  838860800,
       1006632960])

Copies and Views

In [ ]:
arr1

array([ 1,  0,  2,  3,  4, 99,  5, 80])

In [ ]:
a = np.copy(arr1)

In [ ]:
a

array([ 1,  0,  2,  3,  4, 99,  5, 80])

View : just like Shallow copy
(Ex: b=arr1)

In [ ]:
b = arr1.view()

In [ ]:
b

array([ 1,  0,  2,  3,  4, 99,  5, 80])

In [ ]:
b[0]=200

In [ ]:
b

array([200,   0,   2,   3,   4,  99,   5,  80])

In [ ]:
arr1

array([200,   0,   2,   3,   4,  99,   5,  80])

Metrics Library : matlib
1. whatever has been achieved by numpy library also can be achieved by metrics library

In [123]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [124]:
import numpy.matlib as nm 

In [125]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

Matrix : subclass of array

In [126]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

eye : Identity matrix

In [127]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Numpy - linear algebra funcs

In [130]:
arr1 = np.random.randint([[2,3],[4,5]])

In [134]:
arr2 = np.random.randint([[5,3],[2,5]])

In [135]:
arr1

array([[1, 1],
       [2, 4]])

In [136]:
arr2

array([[2, 0],
       [0, 2]])

Dot product or @

In [137]:
np.dot(arr1,arr2)

array([[2, 2],
       [4, 8]])

In [139]:
#Dot product
arr1@arr2

array([[2, 2],
       [4, 8]])

Eigen values, Eigen vectors and many other values are already available in the numpy