In [3]:
import numpy as np

Numpy array manipulation

In [4]:
arr=np.random.randint(1,10,(4,4))

In [5]:
arr

array([[3, 2, 1, 9],
       [9, 6, 5, 9],
       [5, 8, 4, 2],
       [9, 2, 6, 8]])

In [7]:
arr.reshape(8,2)

array([[3, 2],
       [1, 9],
       [9, 6],
       [5, 9],
       [5, 8],
       [4, 2],
       [9, 2],
       [6, 8]])

Transform(180) : rows->col and viceversa

In [8]:
arr.T

array([[3, 9, 5, 9],
       [2, 6, 8, 2],
       [1, 5, 4, 6],
       [9, 9, 2, 8]])

to one dimensional array

In [9]:
arr.flatten()

array([3, 2, 1, 9, 9, 6, 5, 9, 5, 8, 4, 2, 9, 2, 6, 8])

Has parameters as array and axis(for expansion) 
1 axis -across column 
and 
0 across row

In [14]:
np.expand_dims(arr,1)

array([[[3, 2, 1, 9]],

       [[9, 6, 5, 9]],

       [[5, 8, 4, 2]],

       [[9, 2, 6, 8]]])

In [15]:
np.expand_dims(arr,0)

array([[[3, 2, 1, 9],
        [9, 6, 5, 9],
        [5, 8, 4, 2],
        [9, 2, 6, 8]]])

In [16]:
data = np.array([[1],[2],[3]])

Squeeze for 2D to 1D

In [17]:
np.squeeze(data)

array([1, 2, 3])

repeat: arr,repeatition num

In [18]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

Roll(arr,num): rolling of array elements. means rotate by 2. ex: 1 is available at 0th position now it will rotate by 2

In [22]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [23]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

2D diagonal Array

In [28]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Binary Operators : index wise

In [33]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [34]:
arr1

array([[8, 7, 8, 4],
       [7, 5, 9, 5],
       [7, 1, 3, 2]])

In [35]:
arr2

array([[3, 1, 8, 6],
       [2, 1, 6, 3],
       [8, 7, 8, 1]])

In [36]:
arr1+arr2

array([[11,  8, 16, 10],
       [ 9,  6, 15,  8],
       [15,  8, 11,  3]])

In [37]:
arr1*arr2

array([[24,  7, 64, 24],
       [14,  5, 54, 15],
       [56,  7, 24,  2]])

In [38]:
arr1/arr2

array([[2.66666667, 7.        , 1.        , 0.66666667],
       [3.5       , 5.        , 1.5       , 1.66666667],
       [0.875     , 0.14285714, 0.375     , 2.        ]])

In [39]:
arr1-arr2

array([[ 5,  6,  0, -2],
       [ 5,  4,  3,  2],
       [-1, -6, -5,  1]])

In [41]:
#Power operation
arr1**arr2

array([[     512,        7, 16777216,     4096],
       [      49,        5,   531441,      125],
       [ 5764801,        1,     6561,        2]])

In [44]:
arr1

array([[8, 7, 8, 4],
       [7, 5, 9, 5],
       [7, 1, 3, 2]])

In [42]:
# Negation operation
~arr1

array([[ -9,  -8,  -9,  -5],
       [ -8,  -6, -10,  -6],
       [ -8,  -2,  -4,  -3]])

In [43]:
arr1>arr2

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [False, False, False,  True]])

Numpy- String Operations

In [45]:
arr = np.array(["shivi","pinky"])

U5- is data format of the string

In [46]:
arr

array(['shivi', 'pinky'], dtype='<U5')

CHAR

In [47]:
np.char.upper(arr)

array(['SHIVI', 'PINKY'], dtype='<U5')

In [48]:
np.char.capitalize(arr)

array(['Shivi', 'Pinky'], dtype='<U5')

In [49]:
np.char.title(arr)

array(['Shivi', 'Pinky'], dtype='<U5')

In [50]:
arr1

array([[8, 7, 8, 4],
       [7, 5, 9, 5],
       [7, 1, 3, 2]])

In [53]:
#sinusoidal values(sin)
np.sin(arr1)

array([[ 0.98935825,  0.6569866 ,  0.98935825, -0.7568025 ],
       [ 0.6569866 , -0.95892427,  0.41211849, -0.95892427],
       [ 0.6569866 ,  0.84147098,  0.14112001,  0.90929743]])

In [54]:
np.cos(arr1)

array([[-0.14550003,  0.75390225, -0.14550003, -0.65364362],
       [ 0.75390225,  0.28366219, -0.91113026,  0.28366219],
       [ 0.75390225,  0.54030231, -0.9899925 , -0.41614684]])

In [55]:
np.tan(arr1)

array([[-6.79971146,  0.87144798, -6.79971146,  1.15782128],
       [ 0.87144798, -3.38051501, -0.45231566, -3.38051501],
       [ 0.87144798,  1.55740772, -0.14254654, -2.18503986]])

In [57]:
np.log(arr1)

array([[2.07944154, 1.94591015, 2.07944154, 1.38629436],
       [1.94591015, 1.60943791, 2.19722458, 1.60943791],
       [1.94591015, 0.        , 1.09861229, 0.69314718]])

In [58]:
np.exp(arr1)

array([[2.98095799e+03, 1.09663316e+03, 2.98095799e+03, 5.45981500e+01],
       [1.09663316e+03, 1.48413159e+02, 8.10308393e+03, 1.48413159e+02],
       [1.09663316e+03, 2.71828183e+00, 2.00855369e+01, 7.38905610e+00]])

In [59]:
np.power(arr1,2)

array([[64, 49, 64, 16],
       [49, 25, 81, 25],
       [49,  1,  9,  4]], dtype=int32)

In [60]:
np.mean(arr1)

5.5

In [61]:
np.median(arr1)

6.0

In [66]:
np.std(arr1)

2.4664414311581235

In [67]:
np.var(arr1)

6.083333333333333

In [68]:
np.max(arr1)

9

In [69]:
np.min(arr1)

1

Arithmetic Operations

In [70]:
arr1

array([[8, 7, 8, 4],
       [7, 5, 9, 5],
       [7, 1, 3, 2]])

In [71]:
arr2

array([[3, 1, 8, 6],
       [2, 1, 6, 3],
       [8, 7, 8, 1]])

Similar 

In [72]:
arr1-arr2

array([[ 5,  6,  0, -2],
       [ 5,  4,  3,  2],
       [-1, -6, -5,  1]])

In [73]:
np.subtract(arr1,arr2)

array([[ 5,  6,  0, -2],
       [ 5,  4,  3,  2],
       [-1, -6, -5,  1]])

In [74]:
np.multiply(arr1,arr2)

array([[24,  7, 64, 24],
       [14,  5, 54, 15],
       [56,  7, 24,  2]])

In [75]:
np.mod(arr1,arr2)

array([[2, 0, 0, 4],
       [1, 0, 3, 2],
       [7, 1, 3, 0]])

In [77]:
np.power(arr1,arr2)

array([[     512,        7, 16777216,     4096],
       [      49,        5,   531441,      125],
       [ 5764801,        1,     6561,        2]])

In [78]:
np.sqrt(arr1)

array([[2.82842712, 2.64575131, 2.82842712, 2.        ],
       [2.64575131, 2.23606798, 3.        , 2.23606798],
       [2.64575131, 1.        , 1.73205081, 1.41421356]])

In [79]:
np.mean(arr1)

5.5

In [80]:
np.std(arr1)

2.4664414311581235