In [10]:
import numpy as np

Range function just works on integers not on float

In [11]:
list(range(5))

[0, 1, 2, 3, 4]

In [12]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [14]:
list(range(0.4,0.9))

TypeError: 'float' object cannot be interpreted as an integer

np.arange: Same as range function but this also works on float

In [15]:
[np.arange(5,25,0.9)]

[array([ 5. ,  5.9,  6.8,  7.7,  8.6,  9.5, 10.4, 11.3, 12.2, 13.1, 14. ,
        14.9, 15.8, 16.7, 17.6, 18.5, 19.4, 20.3, 21.2, 22.1, 23. , 23.9,
        24.8])]

In [16]:
[np.arange(1.0,5.2,2)]

[array([1., 3., 5.])]

In [17]:
list(np.arange(.4,10.2,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004]

Linspace - gives the elements of equal size(difference). 
* Here below it is generating 20 values btwn 1,5

In [18]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

Logspace - very similar to linspace. but here it generates logarithmic value

In [19]:
#by default base 10
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [20]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

Generates array of zeroes

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
# 2-rows,3-columns
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Here 4,2  are row and column and 3 is the 3 arrays of 4,2 dimensions... We can also think as it is dimension

In [23]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [24]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

Generating array of ones

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
arr = np.ones((3,4))

In [27]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Arithmetic Operations

Adding 5 to each and every element of arr

In [28]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [29]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

Empty

In [30]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [31]:
np.empty((5,7))

array([[1.00001982e-311, 9.99973092e-312, 0.00000000e+000,
        0.00000000e+000, 2.44078969e-154, 1.15998412e-028,
        4.31603868e-080],
       [1.94919985e-153, 1.03063392e-113, 6.03095082e-154,
        4.44891557e-086, 1.08523733e-095, 6.03107600e-154,
        3.25580950e-086],
       [8.97966036e-096, 4.57669512e-072, 4.06011537e-086,
        6.01347176e-154, 2.90852733e-033, 1.05235156e-153,
        7.67941812e-043],
       [1.57753149e-052, 1.05176888e-153, 1.02587682e-071,
        8.54518706e-072, 1.04885545e-153, 1.81148477e-152,
        2.99063837e-067],
       [5.86422986e+294, 3.45365695e+175, 2.77191367e+296,
        2.91237123e+257, 4.71294503e+257, 1.35346062e+295,
        2.22298114e+271]])

Eye : identity/unit matrix

In [32]:
arr1 = np.eye(5)

In [33]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Data frame

In [34]:
import pandas as pd

In [35]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

Generating random numbers array.
*  random.rand : Random values.
*  random.randn : standard normal distribution() - {mean - 0,std -1}
*  random.randint

In [36]:
np.random.rand(2,3)

array([[0.51324039, 0.78890419, 0.68680835],
       [0.19267305, 0.02403756, 0.4783435 ]])

In [38]:
np.random.randn(2,3)

array([[-1.79758577, -1.08087897, -0.79497395],
       [ 0.19093813, -1.21951232,  0.22932979]])

In [95]:
arr2 = np.random.randint(1,5 , (3,4))

In [96]:
arr2

array([[2, 2, 1, 4],
       [4, 4, 3, 3],
       [2, 4, 4, 4]])

Size

In [97]:
arr2.size

12

Shape

In [98]:
arr2.shape

(3, 4)

Reshape : Can reshape in any shape(any dimension 2D,3D or anything") but should have same size(no. of elements)

In [99]:
arr2.reshape(4,3)

array([[2, 2, 1],
       [4, 4, 4],
       [3, 3, 2],
       [4, 4, 4]])

In [100]:
arr2.reshape(6,2)

array([[2, 2],
       [1, 4],
       [4, 4],
       [3, 3],
       [2, 4],
       [4, 4]])

In [101]:
arr2.reshape(2,6)

array([[2, 2, 1, 4, 4, 4],
       [3, 3, 2, 4, 4, 4]])

if we gave -value(-ve) then it will try to adjust shape according to the one parameter given

In [102]:
arr2.reshape(4,-178)

array([[2, 2, 1],
       [4, 4, 4],
       [3, 3, 2],
       [4, 4, 4]])

In [103]:
arr2

array([[2, 2, 1, 4],
       [4, 4, 3, 3],
       [2, 4, 4, 4]])

In [104]:
arr2.reshape(2,2,3)

array([[[2, 2, 1],
        [4, 4, 4]],

       [[3, 3, 2],
        [4, 4, 4]]])

* Overall product should be equal to the number of elements

In [105]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[2]]],


         [[[2]]],


         [[[1]]]],



        [[[[4]]],


         [[[4]]],


         [[[4]]]]],




       [[[[[3]]],


         [[[3]]],


         [[[2]]]],



        [[[[4]]],


         [[[4]]],


         [[[4]]]]]])

Here the numbers will be btwn 1 to 10 and shape of the array eill be 5 and 6

In [51]:
arr1 = np.random.randint(1,10 , (5,6))

In [52]:
arr1

array([[6, 5, 6, 1, 5, 7],
       [4, 7, 5, 5, 7, 1],
       [7, 5, 5, 6, 5, 2],
       [5, 9, 5, 2, 1, 6],
       [9, 6, 8, 5, 7, 1]])

Accessing elements greater than 8

In [54]:
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False, False, False, False]])

In [56]:
arr1[arr1>8]

array([9, 9])

In [57]:
arr1

array([[6, 5, 6, 1, 5, 7],
       [4, 7, 5, 5, 7, 1],
       [7, 5, 5, 6, 5, 2],
       [5, 9, 5, 2, 1, 6],
       [9, 6, 8, 5, 7, 1]])

Accessing of elements : Row will be into ( : ) but rest as indexes

In [58]:
arr1[0,[0,1]]

array([6, 5])

In [59]:
arr1[2:4,[0,1]]

array([[7, 5],
       [5, 9]])

Parallel Operations : same indexes operations

In [60]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [61]:
arr1+arr2

array([[3, 2, 3],
       [3, 4, 2],
       [3, 2, 3]])

In [63]:
arr1*arr2

array([[2, 1, 2],
       [2, 4, 1],
       [2, 1, 2]])

In [65]:
arr1/arr2

array([[2. , 1. , 0.5],
       [0.5, 1. , 1. ],
       [2. , 1. , 2. ]])

Gives infinity in case of arrays instead of error

In [66]:
arr1/0

C:\Users\SHIVANI\AppData\Local\Temp\ipykernel_34876\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

To do matrix multiplication - @

In [64]:
arr1 @ arr2

array([[5, 5, 6],
       [6, 6, 5],
       [6, 6, 7]])

Numpy Broadcasting : doing same operation on all the elements of the array

In [ ]:
arr = np.zeros((3,4))

In [69]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [71]:
a = np.array([1,2,3,4])

In [72]:
arr+a

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [73]:
b = np.array([3,4,5])

Gives error bcoz the operation is not valid for all the elements of the array(arr - not sufficient for applying for all the row elements) 
* To perform we can transpose the b and then apply (applied to all elements column wise)

In [76]:
arr + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [81]:
arr + b.T

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

Still its giving error bcoz we cannot transpose the 1d array so we have to make it 2D

In [79]:
b = np.array([[3,4,5]])

In [83]:
arr1 = arr + b.T

In [84]:
arr1

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

Sqrt, Log, Exp(Exponent function), Min, Max

In [85]:
np.sqrt(arr1)

array([[2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974]])

In [86]:
np.log10(arr1)

array([[0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ],
       [0.77815125, 0.77815125, 0.77815125, 0.77815125]])

In [87]:
np.min(arr1)

4.0

In [88]:
np.max(arr1)

6.0

In [89]:
np.exp(arr1)

array([[ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ],
       [403.42879349, 403.42879349, 403.42879349, 403.42879349]])